<?php


namespace App\Tests\Integration\Narrative;


use App\Repository\FragmentRepository;
use App\Repository\NarrativeRepository;
use App\Repository\QualificationRepository;
use App\Tests\AbstractEdoApiTestCase;
use Doctrine\ORM\EntityManagerInterface;
use Liip\TestFixturesBundle\Test\FixturesTrait;

/**
 * Class AbstractNarrativeResourceTest
 * @package App\Tests\Integration\Narrative
 */
class AbstractNarrativeResource extends AbstractEdoApiTestCase
{
    use FixturesTrait;

    /** @var EntityManagerInterface|object|null  */
    protected $em;

    /** @var array  */
    protected $data;

    /** @var string  */
    protected $title;

    /** @var string  */
    protected $content;

    /** @var NarrativeRepository|object|null  */
    protected $narrativeRepository;

    /** @var FragmentRepository|object|null  */
    protected $fragmentRepository;

    /** @var FragmentRepository|object|null  */
    protected $qualificationRepository;

    public function setUp():void
    {
        parent::setUp();

        $this->title = 'Title example from phpunit';
        $this->content = 'This content is generated by testPostNarrative';

        $this->data = [
            'uuid' => '6153ca18-47a9-4b38-ae72-29e8340060cb',
            'title' => $this->title,
            'content' => $this->content
        ];

        $container = self::$container;

        $this->em = $container->get(EntityManagerInterface::class);

        // list of repositories
        $this->narrativeRepository = $container->get(NarrativeRepository::class);
        $this->fragmentRepository = $container->get(FragmentRepository::class);
        $this->qualificationRepository = $container->get(QualificationRepository::class);
    }
}